export const en = {
  header: {
    home: "home",
    marketplace: "Project",
    news: "news",
    about_us: "About Us",
    partner: "Partner",
    contact: "Contact Us",
  },
  footer: {
    usefull_links: "Usefull links",
    social_media: "Social media",
  },
  balance: "Balance",
  login: "Login",
  phone_number: "Phone number",
  no_account: "Don't have an account yet?",
  register_now: "Register Now",
  market_news: "Market News",
  company_news: "RETX News",
  marketplace: "Project",
  portion: "Fun Unit",
  view_more: "View more",
  metadap_partner: "RETX's Partner",
  about_us: "About Us",
  address: "Address",
  phone: "Phone",
  design_by: "Design by",
  transaction: "Transaction",
  investors: "Investors",
  refresh: "Refresh",
  add_to_cart: "Add To Cart",
  information: "Profile",
  legal: "Legal",
  cash_flow: "Cashflow",
  map: "Map",
  chart: "Chart",
  see_more_product: "See more",
  enter_text: "Enter Text",
  post: "Post",
  feedback_for_this_product: "Feedback for this project",
  latest: "Latest",
  popular: "Popular",
  selersman: "Salersman",
  price: "Price",
  most_view: "Most view",
  most_comment: "Most comment",
  highest_ratting: "Highest ratting",
  portion_price: "Portion price",
  total_price: "Total price",
  portion_number: "Portion number",
  price_low_to_hight: "Price Low To Hight",
  price_hight_to_low: "Price Hight To Low",
  price_range: "Price_range",
  area_range: "Area Range",
  add_location: "Add Location",
  city: "City",
  province: "Province",
  dicstrict: "Dicstric",
  ward: "Ward",
  type_of_asset: "Type of asset",
  direction_of_asset: "The direction of asset",
  my_account: "My Account",
  register: "Register",
  about_metadap: "About RETX",
  metadap_team: "RETX Team",
  advisor: "Advisor",
  text_search_bar: "Project searching",
  buy: "Buy",
  sell: "Sell",
  confirm: "Confirm",
  sold: "sold",
  send_us_a_message: "Send Us A Message",
  fullname: "Fullname",
  email: "Email",
  message: "Message",
  send: "Send",
  password: "Password",
  search: "Search",
  all: "All",
  logout: "Logout",
  new_product: "New Project",
  welcome_retx: "Welcome to RETX",
  view_all: "View all",
  question_and_answer: "Question and Answer",
  verify_kyc: "Verify KYC",
  login_now: "Login now",
  updating: "Updating",
  ratting_and_comment: "Rating and comment",
  write_comment: "Write comment",
  submit_ratting: "Submit",
  write_question: "Write question",
  submit_question: "Submit",
  average_rating: "Average rating",
  reply: "Reply",
  minimum_8_characters: "Minimum 8 characters",
  at_least_1_digit: "At least 1 digit",
  confirm_password: "Confirm password",
  i_agree_with_policy: "I agree with Terms and Privacy Policy of RETX",
  next: "Next",
  later: "Later",
  msg_error_input_require: "This is a required field",
  msg_error_input_confirm_password: "Please make sure your passwords match",
  phone_number_invalid: "Phone number is invalid",
  must_agree_to_policy: "You must agree to the Terms and Privacy Policy",
  verify_your_email: "Verify your email",
  your_verification_code_is_sent_by_email_to:
    "Your verification code is sent by email to",
  effective_for: "Effective for",
  enter_verification_code: "Enter verification code",
  resend_verification_code: "Resend verification code",
  do_yout_want_to_perform_identity:
    "Do yout want to perform identity KYC \n verification to start trading",
  only_kyc_verified_accounts_can:
    "Only KYC verified accounts can rate and trade products",
  kyc_pending: "KYC pending",
  msg_error_email_exist: "Email is exist",
  msg_error_phone_number_exist: "Phone number is exist",
  code_has_expired: "Code has expired",
  code_is_wrong: "Code is wrong",
  unverified_data: "Unverified data",
  forgot_password: "Forgot password",
  do_not_have_an_account_yet: "Don't have an account yet",
  identity_verification_process: "Identity verification process",
  please_take_pictures_valid_papers_original_photos:
    "Please take pictures valid papers, original photos",
  select_the_type_of_document: "Select the type of document",
  id_card: "Id card",
  front_side: "Front side",
  back_side: "Back side",
  upload_image: "Upload image",
  valid: "Valid",
  id_no: "Id no",
  sex: "Sex",
  issued_date: "Issued date",
  issued_by: "Issued by",
  remove_image: "Remove image",
  loading: "Loading",
  processing: "Processing",
  check_information_to_complete:
    "CHECK INFORMATION TO COMPLETE\nINDENTITY VERIFICATION PROCESS",
  upload_avatar: "Upload avatar",
  enter_password_to_complete_verification_process:
    "Enter password to complete\nverification process",
  identity_verification_process_is_complete:
    "INDENTITY VERIFICATION PROCESS\nIS COMPLETED",
  i_am_human: "I'm not a robot",
  you_is_robot: "You is robot",
  account_is_not_exist: "Account is not exist",
  account_is_not_active: "Account is not active",
  resend_verification_code_to_your_email_successfully:
    "Resend verification code to your email successfully",
  your_account: "Your account",
  change_password: "Change password",
  for_your_account_is_security_do_not_share_your_password_with_anyone_else:
    "For your account's security, do not share your password with anyone else",
  new_password: "New password",
  confirm_new_password: "Confirm new password",
  change_password_successfully: "Change password successfully",
  account_metamask_current_used:
    "The current metamask account is already in used",
  link_metamask_with_smartcontract_fail:
    "Link metamask with smart contract fail",
  connect_fail_please_try_again: "Verify fail, please try again",
  your_address_is_invalid_or_already_registed:
    "Your address is invalid or already registed",
  send_success: "Send successfully",
  verify_your_bep20_address: "VERIFY YOUR BEP20 ADDRESS",
  connect_success: "Connect success",
  your_address: "Your address",
  this_function_is_only_excuted_on_desktops:
    "This function is only excuted on desktops",
  skip: "Skip",
  verify: "Verify",
  connect_BEP20_wallet: "Connect BEP20 Wallet",
  login_and_connect_web3: "Login & connect Web3",
  password_incorrect: "Password incorrect",
  add_to_cart_success: "Add to cart successfully",
  the_product_is_already_in_your_cart: "The product is already in your cart",
  you_need_to_sign_in: "You need to sign in",
  login_successfully: "Login successfully",
  login_faild: "Login failed",
  you_need_to_fill_in_the_content: "You need to fill in the content",
  name: "Name",
  my_portion: "No. of Fun Unit",
  value_of_portion: "Price per Fun Unit",
  no_data: "No data",
  asset: "Asset",
  rating: "Rating",
  content: "Content",
  please_contact_to_update_kyc_information:
    "Please contact 091 969 6000 to update KYC information!",
  email_is_exist: "Email is exist",
  birthday: "Birthday",
  code_verification: "Code verification",
  expires_in: "Expires in",
  update_email: "Update email",
  update_email_successfully: "Update email successfully",
  current_password: "Current password",
  save: "Save",
  update_avatar: "Update avatar",
  please_contact_to_top_up_your_account:
    "Please contact 091 969 6000 to top up your account!",
  address_wallet: "Address wallet",
  cart: "Cart",
  my_rating: "My rating",
  user_is_tern_and_privacy_policy: "User's Term and Privacy Policy",
  top_up_VND: "Top up VND",
  send_code_verification: "Send code verification",
  incorrect_username_or_password: "Incorrect username or password",
  inactive_account: "Inactive account",
  id_card_exist: "Id card exist",
  update_new_email: "Update new email",
  new_email: "New email",
  remove_from_cart: "Remove from cart",
  please_input_new_assword: "Please input new password",
  validate_current_email: "Validate current email",
  sending_verification_code_to: "Sending verification code to",
  please_verify_wallet_to_securely_store_and_trade_your_assets:
    "Please Verify Wallet to securely store and trade your assets",
  connect_web3: "Connect web3",
  verify_wallet: "Verify wallet",
  you_need_to_verify_wallet: "You need to verify wallet",
  you_need_install_metamask: "You need to install and enable Metamask",
  notification: "Notification",
  the_address_not_match_the_registered_account_address:
    "The address does not match the registered account address",
  no_search_history_yet: "No search history yet",
  the_connected_wallet_address_does_not_match:
    "The connected wallet address does not match",
  verify_your_phone_number: "Verify your phone number",
  your_verification_code_is_sent_to_phone_number:
    "Verification code is sent to phone number",
  resend_verification_code_to_your_phone_number_successfully:
    "Resend verification code to your phone number successfully",
  validate_current_phone: "Validate current phone number",
  update_new_phone: "Update new phone number",
  new_phone: "New phone number",
  update_phone_successfully: "Update phone number successfully",
  history_transaction_VND: "Transaction P2P VND",
  sender: "Sender",
  receiver: "Receiver",
  to: "To",
  amount: "Amount",
  time: "Time",
  from: "From",
  status: "Status",
  method: "Method",
  the_wallet_connection_is_not_correct: "The wallet connection is not correct",
  wallet_not_connected: "Wallet not connected",
  carrier_does_not_support: "This network home not support",
  approved: "Approved",
  insufficient_balance: "Insufficient balance",
  deposit_withdraw: "Deposit/Withdraw money",
  you_need_to_evaluate_stars: "You need to evaluate stars",
  view_transactions: "View transactions",
  email_is_wrong_format: "Email is wrong format",
  copy_successfully: "Copy successfully",
  cancelled: "Cancelled",
  pending: "Pending",
  initialize: "Initialize",
  failed: "Failed",
  success: "Success",
  refund: "Refund",
  expired: "Expired",
  "half-done": "Half-done",
  done: "Done",
  withdraw: "Withdraw",
  deposit: "Deposit",
  withdrawal_history: "Withdrawal history",
  recharge_history: "Deposit history",
  amount_you_want_to_deposit: "Amount you want to deposit?",
  amount_you_want_to_withdraw: "Amount you want to withdraw?",
  receive_bank: "Receive bank",
  receive_account_name: "Receive account name",
  receive_account_number: "Receive account number",
  you_need_KYC_erification_to_be_able_to_make_transactions:
    "You need KYC verification to be able to make transactions",
  we_are_verifying_your_information_please_return_to_trading_in_24h:
    "We are verifying your information. Please return to trading in 24h",
  choose_a_bank: "Choose a bank",
  deposit_order_placed: "Deposit order placed",
  please_pay_within: "Please pay within",
  amount_to_transfer: "Amount to transfer",
  minute: "minutes",
  second: "seconds",
  transfer_contents: "Transfer contents",
  please_transfer_the_amount: "Please transfer the amount",
  to_the_account_you_selected_with_the_transfer_content_is:
    "to the account you selected with the transfer content is",
  then_click_transferred_button: 'Then click "Transferred" button.',
  transferred: "Transferred",
  cancel_transaction: "Cancel transaction",
  withdrawal_order_placed: "Withdrawal order placed",
  please_wait_for_us_to_process_your_request_in_another_24_hours:
    "Please wait for us to process your request in another 24 hours",
  submit_a_withdrawal_request: "Submit a withdrawal request",
  cancel_withdrawal_request: "Cancel withdrawal request",
  feadback: "Feadback",
  withdrawal_request_successful: "Withdrawal request successful",
  price_impact: "Price impact",
  liquidity_provider_fee: "Liquidity provider fee",
  impact_price_too_high: "Impact price too high",
  sms_otp_authentication: "SMS OTP Authentication",
  otp_has_been_sent_to_your_phone_number:
    "OTP has been sent to your phone number",
  please_enter_OTP_to_continue: "please enter OTP to continue",
  the_system_has_recorded_your_transaction_and_the_transaction_will_be_processed_within_30_minutes_please_wait:
    "The system has recorded your transaction and the transaction will be processed within 30 minutes, please wait!",
  circulating: "Circulating",
  this_feature_is_only_operated_on_the_computer:
    "This feature is only operated on the computer",
  comment_successfully: "Comment successfully",
  verify_withdrawal_order: "Verify withdrawal order",
  recharge_now: "Recharge now",
  transaction_confirmation: "Transaction confirmation",
  you_must_have_read_and_understood_about_this_product:
    "You must have read and understood about this product",
  you_agree_and_undertake_to_comply_with_the_release_and_withdrawal_policies_listed_in_the_Legal_tab:
    "You agree and undertake to comply with the release and withdrawal policies listed in the Legal tab",
  you_are_solely_responsible_for_this_decision:
    "You are solely responsible for this decision",
  don_t_ask_again: "Don't ask again",
  disagree: "Disagree",
  agree: "Agree",
  please_enter_the_OTP_sent_to_your_phone_number:
    "Please enter the OTP sent to your phone number",
  wrong_wallet_address: "Wrong wallet address",
  correct_wallet_address: "Correct wallet address",
  wallet_connection_is_not_completed: "Wallet connection is not completed",
  confirmed_transfer: "Confirmed transfer",
  transaction_successful: "Transaction successful",
  transaction_failed: "Transaction failed",
  check_your_metamask_network: "Check your metamask network",
  we_currently_do_not_support_this_network:
    "We currently do not support this network",
  please_select_your_network_to_continue:
    "Please change your network to continue",
  network_switch_in_wallet: "Switch network in wallet",
  developing: "Developing",
  not_connected_to_the_network: "Not connected to the network",
  about_paragraph_1:
    "is the first technology platform in Vietnam to apply the common buying model in the field of real estate investment.",
  about_paragraph_2:
    'RETX applies Blockchain technology to digitize Real Estate (Real Estate) into digital assets on the Blockchain platform. Each real estate will be issued its own type of Security Token called Security Token. Each token corresponds to 1/1000 of the value of the property. This mechanism helps retail investors in the market also have the ability to "buy together" in real estate of great value.',
  about_paragraph_3:
    "With this real estate-to-digital asset conversion protocol, RETX opens up investment opportunities in the potential Vietnamese real estate market with just a few taps.",
  about_paragraph_4: "WHY CHOOSE RETX?",
  about_paragraph_5:
    "Help sellers reach millions of investors at once. As a result, real estate is easier to sell and is sold at a better price.",
  about_paragraph_6:
    "RETX contributes to market liquidity and helps investors buy and sell. Transactions are easier and more transparent.",
  about_paragraph_7:
    "RETX has transaction traceability. The transaction history for each identifier is securely stored and easily verified quickly.",
  about_paragraph_8: "RETX – SOLUTION FOR REAL ESTATE MARKET WITHOUT INTEREST",
  about_paragraph_9:
    "Brokers, lawyers, and banks have long been part of the real estate ecosystem. However, RETX can now change that role in real estate transactions. RETX functions can take on functions such as listing, billing and providing legal documentation.",
  about_paragraph_10:
    "Cutting out the middleman will help buyers and sellers maximize profits because they save on commissions and fees for these intermediaries. This also makes the transaction process much faster.",
  about_paragraph_11: "SAFETY AND SECURITY",
  about_paragraph_12:
    "Transactions at RETX are only successful when the identifiers have been verified and the transaction history for each identifier will be securely stored and easily verified quickly. At the same time, RETX only encrypts secured real estate according to Vietnamese law and appraisers. RETX will also automatically calculate taxes and fees on each transaction according to the current regulations of the Sandbox testing framework.",
  about_paragraph_13: "OPPORTUNITY FOR SMALL INVESTORS",
  about_paragraph_14:
    "The division of real estate value (Tokenization) will create a playground for everyone, especially retail investors. Instead of having hundreds of millions or tens of billions to own real estate, with the RETX platform, small investors with very little money can also invest.",
  about_paragraph_15: "SUPPORT TOOLS FOR PROJECT OWNERS",
  about_paragraph_16:
    "Today, due to the prolonged epidemic situation, many real estate investors have difficulty selling real estate or projects. Understanding that need, RETX was born not only to serve sellers but also to support project owners to access new ways of raising capital, removing bottlenecks in the liquidity process of the market.",
  about_paragraph_0: "INTRODUCTION TO RETX",
  project: "Project",
  price_not_updated_yet: "Price not updated yet",
  seller: "Seller",
  property_type: "Property type",
  direction: "Direction",
  location: "Location",
  area: "Area",
  valuation: "Valuation",
  releasePolicy: "Issue Policy",
  recoveryPolicy: "Revoke Policy",
  legalOfProperty: "Legal Of Property",
  valuation_level: "Valuation level",
  effect: "Effect",
  valuation_unit: "Valuation Unit",
  notarization_unit: "Notarization unit",
  notarization_date: "Notarization date",
  parties_join_in_notarization: "Parties involved in notarization",
  inspection_unit: "Inspection unit",
  inspection_date: "Inspection date",
  main_content: "Main content",
  view_file_scan: "View file scan",
  legal_documents_have_been_NFTized: "Legal documents have been NFTized",
  product_is_being_protected_by: "Product is being protected by",
  red_book: "Red book",
  have_red_book: "Have red book",
  have_not_red_book: "Haven't red book",
  dispute: "Dispute",
  have_dispute: "Have dispute",
  have_not_dispute: "Haven't dispute",
  stop_trading: "Suspend trading",
  view_public_records_at_IPFS: "View public records at IPFS",
  sorted_by: "Sorted by",
  creation_time: "Creation time",
  count_view: "Count view",
  discussion: "Discussion",
  total_supply: "Total supply",
  oldest: "Oldest",
  most: "Most",
  least: "Least",
  highest: "Highest",
  lowest: "Lowest",
  choose_a_seller: "Choose a seller",
  choose_an_asset_type: "Choose an asset type",
  choose_city: "Choose city",
  choose_district: "Choose district",
  choose_ward: "Choose ward",
  choose_direction: "Choose direction",
  unchecked: "Unchecked",
  project_owner: "Project owner",
  choose_a_project_owner: "Select a project owner",
  type_project: "Project type",
  select_a_project_type: "Select a project type",
  issue: "Issue",
  purpose: "Purpose",
  policy_and_legal_status_of_und_unit: "Policy and legal status of Fund Unit",
  information_and_legality_of_the_collateral:
    "Information and legality of the Collateral",
  lock_content_1:
    "Protect and ensure assets are not changed hands while the project is operating on the RETX application",
  lock_content_2:
    "Release assets when the terms of the revoke policies are satisfied",
  lock_content_3:
    "Coordinate asset handling in case the project owner fails to comply or loses the ability to perform the committed obligation (to compensate investors)",
  is_responsible_for: "is responsible for",
  lock: "Lock",
  project_procedures: "Project procedures",
  project_procedures_title_box:
    "To ensure integrity and transparency, project procedures are converted to NFT at",
  swap_note_1:
    "Since RETX does not hold your assets, RETX needs to be authorized to make this transaction",
  swap_note_2:
    "RETX has been authorized by you to execute the transaction, click NEXT for the transaction to be executed",
  there_are_number_search_results_for_the_keyword:
    "There are :number search results for the keyword",
  exact_search: "Exact search",
  retx_automatically_optimizes_the_buy_price_at_the_lowest_level:
    "RETX automatically optimizes the buy price at the lowest level",
  over_pool_size: "Over pool size",
  product_suggested: "Product suggested",
  term: "Term",
  you_need_to_connect_the_wallet: "You need to connect Metamask wallet",
  the_account_does_not_exist_in_the_system:
    "The account does not exist in the system",
  identity_verification_to_set_up: "Identity verification to set up",
  awaiting_identity_verification: "Awaiting identity verification",
  project_information: "Project information",
  avatar: "Avatar",
  basic_information: "Basic information",
  verify_now: "Verify now",
  view_results: "View results",
  section_filter: "Filter",
  percentage: "Percentage",
  you_have_request_more_than_allowed: "You have request more than allowed",
  transfers: "Transfers",
  authorization_failed_please_try_again_later:
    "Authorization failed, please try again later",
  web3_data_retrieval_failed: "Web3 data retrieval failed",
  not_open_for_sale_yet: "Not open for sale yet",
  register_success: "Register successfully",
  certificate_of_investment: "Certificate of investment",
  certificate_of_ownership: "Certificate of ownership",
  price_fluctuations: "Price fluctuations",
  certificate_type: "Certificate type",
  product: "Product",
  investment: "Investment",
  own: "Own",
  "explore-section-paragraph-1": "Become a Real Estate Investor today",
  "explore-section-paragraph-2": "The investment is secured by real estate",
  explore_now: "Explore now",
  owner_information: "Owner information",
  join_date: "Join date",
  product_order_number: "Product order number",
  numerical_order: "Numerical order",
  choose: "Choose",
  product_name: "Product's name",
  description: "Description",
  do_you_own_this_product: "Do you own this product",
  you_have_not_posted_this_product_for_sale_yet:
    "You have not posted this product for sale yet",
  sell_now: "Sell now",
  you_are_selling_this_product: "You are selling this product",
  cancel_sale: "Cancel sale",
  owner: "Owner",
  buy_now: "Buy now",
  you_have_made_an_offer_do_you_want_to_cancel_to_continue:
    "You have made an offer, do you want to cancel to continue",
  offer_to_negotiate: "Offer to negotiate",
  your_balance_is_not_enough_do_you_want_to_top_up_to_continue:
    "Your balance is not enough, do you want to top up to continue",
  yes: "Yes",
  no: "No",
  the_product_is_not_for_sale: "The product is not for sale",
  the_owner_has_not_posted_this_product_for_sale:
    "The owner has not posted this product for sale",
  contact_the_owner: "Contact the owner",
  cancel: "Cancel",
  negotiable_List: "Negotiable List",
  mine: "Mine",
  negotiating_party: "Negotiating party",
  desired_price: "Desired price",
  action: "Action",
  agree_to_sell: "Agree to sell",
  suggested_purchase_price: "Suggested purchase price",
  transaction_fee: "Transaction fee",
  amount_earned: "Amount earned",
  i_agree_to_and_abide_by_RETX_policy: "I agree to and abide by :RETX_policy",
  RETX_policy: "RETX's policy",
  amount_you_have_to_pay: "Amount you have to pay",
  amount_received_by_the_seller: "Amount received by the seller",
  user_unregistered_address: "User unregistered address",
  cancellation_of_negotiation: "Cancellation of negotiation",
  desired_selling_price: "Desired selling price",
  desired_purchase_price: "Desired purchase price",
  you_need_to_agree_to_the_terms: "You need to agree to the terms",
  minimum_price_is: "Minimum price is :amount",
  for_sale: "For sale",
  trading_results:"Trading results",
  trading_code: 'Trading code',
  close: 'Close',
  amount_of_assets: "Amount of assets",
  owned_asset: "Owned asset",
  asset_is_paying_price: "Asset is paying price",
  see_price_negotiable: 'See price negotiable',
  circulate: "Circulate",
  trading: "Trading",
  type: "Type",
  resend_OTP_successfully: "Resend OTP successfully",
  removed_from_cart_successfully: "Removed from cart successfully",
  single_asset: "Single asset",
  collection_asset: "Collection asset",
  pause_calling_for_capital: "Pause calling for capital",
  pool_is_not_open_yet: "Pool is not open yet",
  certificate: "Certificate",
  selling_price: "Selling price",
  negotiate: "Negotiate"
};
