export const vi = {
  header: {
    home: "Trang chủ",
    marketplace: "Dự án",
    news: "Tin tức",
    about_us: "Giới thiệu",
    partner: "Đối tác",
    contact: "Liên hệ",
  },
  footer: {
    usefull_links: "Liên kết",
    social_media: "Đa phương tiện",
  },
  balance: "Số dư",
  login: "Đăng nhập",
  phone_number: "Số điện thoại",
  no_account: "Chưa có tài khoản?",
  register_now: "Đăng ký ngay",
  market_news: "Tin tức thị trường",
  company_news: "Tin tức RETX",
  marketplace: "Dự án",
  portion: "Chứng Chỉ",
  view_more: "Xem thêm",
  metadap_partner: "Đối tác RETX",
  about_us: "Giới thiệu",
  address: "Địa chỉ",
  phone: "Điện thoại",
  design_by: "Thiết kế bởi",
  transaction: "Giao dịch",
  investors: "Nhà đầu tư",
  refresh: "Làm mới",
  add_to_cart: "Thêm vào giỏ hàng",
  information: "Thông tin cá nhân",
  legal: "Pháp lý",
  cash_flow: "Dòng tiền",
  map: "Bản đồ",
  chart: "Biểu đồ",
  see_more_product: "Xem thêm",
  enter_text: "Nhập",
  post: "Đăng",
  feedback_for_this_product: "Đánh giá dự án",
  latest: "Mới nhất",
  popular: "Phổ biến",
  selersman: "Người bán",
  price: "Giá",
  most_view: "Xem nhiều",
  most_comment: "Bình luận nhiều",
  highest_ratting: "Đánh giá cao",
  portion_price: "Giá phần", // remove
  total_price: "Giá tổng", // remove
  portion_number: "Số Chứng Chỉ", // remove
  price_low_to_hight: "Thấp đến cao",
  price_hight_to_low: "Cao đến thấp",
  price_range: "Phạm vi giá",
  area_range: "Diện tích",
  add_location: "Vị trí",
  city: "Thành phố",
  province: "Tỉnh",
  dicstrict: "Quận/Huyện",
  ward: "Phường",
  type_of_asset: "Loại hình tài sản",
  direction_of_asset: "Hướng",
  my_account: "Tài khoản",
  register: "Đăng ký",
  about_metadap: "Giới thiệu về RETX",
  metadap_team: "Đội ngũ RETX",
  advisor: "Cố vấn",
  text_search_bar: "Tìm kiếm dự án",
  buy: "Mua",
  sell: "Bán",
  confirm: "Xác nhận",
  sold: "Đã bán",
  send_us_a_message: "Gửi Tin Nhắn Cho Chúng Tôi",
  fullname: "Họ và tên",
  email: "Email",
  message: "Tin nhắn",
  send: "Gửi",
  password: "Mật khẩu",
  search: "Tìm kiếm",
  all: "Tất cả",
  logout: "Đăng xuất",
  new_product: "Dự án mới nhất",
  welcome_retx: "Chào mừng đến với RETX",
  view_all: "Xem tất cả",
  question_and_answer: "Hỏi và đáp",
  verify_kyc: "Xác thực tài khoản",
  login_now: "Đăng nhập ngay",
  updating: "Đang cập nhật",
  ratting_and_comment: "Đánh giá và nhận xét",
  write_comment: "Viết nhận xét của bạn",
  submit_ratting: "Gửi đánh giá",
  write_question: "Viết câu hỏi",
  submit_question: "Gửi câu hỏi",
  average_rating: "Đánh giá trung bình",
  reply: "Trả lời",
  minimum_8_characters: "Tối thiểu 8 ký tự",
  at_least_1_digit: "Ít nhất 1 chữ số",
  confirm_password: "Nhập lại mật khẩu",
  i_agree_with_policy:
    "Tôi đồng ý với các Điều khoản và Chính sách Bảo mật của RETX",
  next: "Tiếp theo",
  later: "Để sau",
  msg_error_input_require: "Đây là thông tin cần thiết",
  msg_error_input_confirm_password: "Mật khẩu nhập lại không trùng khớp",
  phone_number_invalid: "Số điện thoại không hợp lệ",
  must_agree_to_policy:
    "Bạn phải đồng ý với các Điều khoản và Chính sách Bảo mật",
  verify_your_email: "Xác thực email của bạn",
  your_verification_code_is_sent_by_email_to: "Mã xác thực email đã gửi đến",
  effective_for: "Hiệu lực trong",
  enter_verification_code: "Nhập mã xác thực",
  resend_verification_code: "Gửi lại mã xác thực",
  do_yout_want_to_perform_identity:
    "Bạn có muốn thực hiện xác minh KYC \n để bắt đầu giao dịch không",
  only_kyc_verified_accounts_can:
    "Chỉ những tài khoản đã xác thực KYC mới có thể đánh giá sản phẩm và thực hiện giao dịch",
  kyc_pending: "Đang chờ xử lý KYC",
  msg_error_email_exist: "Email đã tồn tại",
  msg_error_phone_number_exist: "Số điện thoại đã tồn tại",
  code_has_expired: "Mã đã hết hạn",
  code_is_wrong: "Mã không đúng",
  unverified_data: "Dữ liệu chưa được xác thực",
  forgot_password: "Quên mật khẩu",
  do_not_have_an_account_yet: "Bạn không có tài khoản",
  identity_verification_process: "Quy trình xác minh danh tính",
  please_take_pictures_valid_papers_original_photos:
    "Vui lòng chụp ảnh giấy tờ hợp lệ, ảnh gốc",
  select_the_type_of_document: "Chọn loại tài liệu",
  id_card: "CMND/CCCD",
  front_side: "Mặt trước",
  back_side: "Mặt sau",
  upload_image: "Tải ảnh lên",
  valid: "Hợp lệ",
  id_no: "Số ID",
  sex: "Giới tính",
  issued_date: "Ngày cấp",
  issued_by: "Nơi cấp",
  remove_image: "Xóa ảnh",
  loading: "Đang tải...",
  processing: "Đang xử lý",
  check_information_to_complete:
    "KIỂM TRA THÔNG TIN ĐỂ HOÀN THÀNH\nQUY TRÌNH XÁC MINH NHẬN DẠNG",
  upload_avatar: "Tải ảnh đại diện",
  enter_password_to_complete_verification_process:
    "Nhập mật khẩu để hoàn tất\nquá trình xác minh",
  identity_verification_process_is_complete:
    "QUÁ TRÌNH XÁC MINH NHẬN DẠNG\nĐÃ HOÀN THÀNH",
  i_am_human: "Tôi không phải robot",
  you_is_robot: "Bạn là người máy",
  account_is_not_exist: "Tài khoản không tồn tại",
  account_is_not_active: "Tài khoản chưa kích hoạt",
  resend_verification_code_to_your_email_successfully:
    "Gửi lại mã xác thực về  email của bạn thành công",
  your_account: "Tài khoản của bạn",
  change_password: "Thay đổi mật khẩu",
  for_your_account_is_security_do_not_share_your_password_with_anyone_else:
    "Để bảo mật cho tài khoản của bạn, không chia sẻ mật khẩu của bạn với bất kỳ ai khác",
  new_password: "Mật khẩu mới",
  confirm_new_password: "Xác nhận mật khẩu mới",
  change_password_successfully: "Thay đổi mật khẩu thành công",
  account_metamask_current_used: "Tài khoản metamask hiện tại đã được sử dụng",
  link_metamask_with_smartcontract_fail:
    "Liên kết tài khoản metamask với smart contract thất bại",
  connect_fail_please_try_again: "Xác thực thất bại, hãy thử lại",
  your_address_is_invalid_or_already_registed:
    "Địa chỉ ví không hợp lệ hoặc đã được đăng ký",
  send_success: "Gửi thành công",
  verify_your_bep20_address: "Xác thực địa chỉ BEP20 của bạn ",
  connect_success: "Kết nối thành công",
  your_address: "Địa chỉ của bạn",
  this_function_is_only_excuted_on_desktops:
    "Tính năng này chỉ thực hiện được trên desktop",
  skip: "Bỏ qua",
  verify: "Xác thực",
  connect_BEP20_wallet: "Kết nối địa chỉ BEP20",
  login_and_connect_web3: "Đăng nhập & Kết nối Web3",
  password_incorrect: "Mật khẩu không đúng",
  add_to_cart_success: "Thêm vào giỏ hàng thành công",
  the_product_is_already_in_your_cart: "Dự án đã có trong giỏ hàng của bạn",
  you_need_to_sign_in: "Bạn cần đăng nhập",
  login_successfully: "Đăng nhập thành công",
  login_faild: "Đăng nhập thất bại",
  you_need_to_fill_in_the_content: "Bạn cần điền nội dung",
  name: "Tên",
  my_portion: "Số Chứng Chỉ",
  value_of_portion: "Giá mỗi Chứng Chỉ",
  no_data: "Không có dữ liệu",
  asset: "Tài sản",
  rating: "Đánh giá",
  content: "Nội dung",
  please_contact_to_update_kyc_information:
    "Liên hệ 091 969 6000 để cập nhật thông tin KYC!",
  email_is_exist: "Email đã tồn tại",
  birthday: "Sinh nhật",
  code_verification: "Mã xác thực",
  expires_in: "Hết hạn trong",
  update_email: "Cập nhật email",
  update_email_successfully: "Cập nhật email thành công",
  current_password: "Mật khẩu hiện tại",
  save: "Lưu",
  update_avatar: "Cập nhật ảnh đại diện",
  please_contact_to_top_up_your_account:
    "Liên hệ 091 969 6000 để nạp tiền vào tài khoản! ",
  address_wallet: "Địa chỉ ví",
  cart: "Giỏ hàng",
  my_rating: "Đánh giá của tôi",
  user_is_tern_and_privacy_policy:
    "Điều khoản của Người dùng và Chính sách Quyền riêng tư",
  top_up_VND: "Nạp tiền VND",
  send_code_verification: "Gửi mã xác thực",
  incorrect_username_or_password: "Tài khoản hoặc mật khẩu không đúng",
  inactive_account: "Tài khoản chưa hoạt động",
  id_card_exist: "CMND/CCCD đã tồn tại",
  update_new_email: "Cập nhật email mới",
  new_email: "Email mới",
  remove_from_cart: "Bỏ khỏi giỏ hàng",
  please_input_new_assword: "Vui lòng nhập mật khẩu mới",
  validate_current_email: "Xác thực email hiện tại",
  sending_verification_code_to: "Đang gửi mã xác thực đến",
  please_verify_wallet_to_securely_store_and_trade_your_assets:
    "Xác thực ví để lưu trữ và giao dịch an toàn tài sản của bạn",
  connect_web3: "Kết nối ví",
  verify_wallet: "Xác thực ví",
  you_need_to_verify_wallet: "Bạn cần xác thực địa chỉ ví",
  you_need_install_metamask: "Bạn cần cài đặt và bật metamask",
  notification: "Thông báo",
  the_address_not_match_the_registered_account_address:
    "Địa chỉ không trùng khớp với địa chỉ đã đăng ký tài khoản",
  no_search_history_yet: "Chưa có lịch sử tìm kiếm",
  the_connected_wallet_address_does_not_match:
    "Địa chỉ ví đã kết nối không trùng khớp",
  verify_your_phone_number: "Xác thực số điện thoại của bạn",
  your_verification_code_is_sent_to_phone_number:
    "Mã xác minh của bạn đã gửi đến số điện thoại",
  resend_verification_code_to_your_phone_number_successfully:
    "Gửi lại mã xác thực về số điện thoại của bạn thành công",
  validate_current_phone: "Xác thực số điện thoại hiện tại",
  update_new_phone: "Cập nhật số điện thoại mới",
  new_phone: "Số điện thoại mới",
  update_phone_successfully: "Cập nhật số điện thoại thành công",
  history_transaction_VND: "Giao dịch P2P VND",
  sender: "Người gửi",
  receiver: "Người nhận",
  to: "Đến",
  amount: "Số lượng",
  time: "Thời gian",
  from: "Từ",
  status: "Trạng thái",
  method: "Phương thức",
  the_wallet_connection_is_not_correct: "Ví kết nối không đúng",
  wallet_not_connected: "Chưa kết nối ví",
  carrier_does_not_support: "Chưa hỗ trợ nhà mạng này",
  approved: "Uỷ quyền",
  insufficient_balance: "Số dư không đủ",
  deposit_withdraw: "Nạp/Rút tiền",
  you_need_to_evaluate_stars: "Bạn cần đánh giá sao",
  view_transactions: "Xem giao dịch",
  email_is_wrong_format: "Email sai định dạng",
  copy_successfully: "Sao chép thành công",
  cancelled: "Đã hủy",
  pending: "Đang chờ",
  initialize: "Khởi tạo",
  failed: "Thất bại",
  success: "Thành công",
  refund: "Hoàn tiền",
  expired: "Hết hạn",
  "half-done": "Tiến độ 50%",
  done: "Xử lý xong",
  withdraw: "Rút tiền",
  deposit: "Nạp tiền",
  withdrawal_history: "Lịch sử rút tiền",
  recharge_history: "Lịch sử nạp tiền",
  amount_you_want_to_deposit: "Số tiền bạn muốn nạp?",
  amount_you_want_to_withdraw: "Số tiền bạn muốn rút?",
  receive_bank: "Ngân hàng nhận",
  receive_account_name: "Tên tài khoản nhận",
  receive_account_number: "Số tài khoản nhận",
  you_need_KYC_erification_to_be_able_to_make_transactions:
    "Bạn cần xác thực KYC để có thể thực hiện giao dịch",
  we_are_verifying_your_information_please_return_to_trading_in_24h:
    "Chúng tôi đang xác thực thông tin của bạn. Vui lòng quay lại giao dịch trong 24h",
  choose_a_bank: "Chọn ngân hàng",
  deposit_order_placed: "Đã đặt lệnh nạp",
  please_pay_within: "Vui lòng thanh toán trong vòng",
  amount_to_transfer: "Số tiền cần chuyển",
  minute: "phút",
  second: "giây",
  transfer_contents: "Nội dung chuyển khoản",
  please_transfer_the_amount: "Vui lòng chuyển khoản số tiền",
  to_the_account_you_selected_with_the_transfer_content_is:
    "đến tài khoản mà bạn đã chọn với nội dung chuyển khoản là",
  then_click_transferred_button: 'Sau đó bấm nút "Đã chuyển khoản"',
  transferred: "Đã chuyển khoản",
  cancel_transaction: "Hủy bỏ giao dịch",
  withdrawal_order_placed: "Đã đặt lệnh rút tiền",
  please_wait_for_us_to_process_your_request_in_another_24_hours:
    "Vui lòng đợi chúng tôi xử lý yêu cầu của bạn trong 24 giờ nữa nhé",
  submit_a_withdrawal_request: "Gửi yêu cầu rút tiền",
  cancel_withdrawal_request: "Hủy yêu cầu rút tiền",
  feadback: "Phản hồi",
  withdrawal_request_successful: "Yêu cầu rút tiền thành công",
  price_impact: "Giá tác động",
  liquidity_provider_fee: "Phí nhà cung cấp thanh khoản",
  impact_price_too_high: "Tác động đến giá quá cao",
  sms_otp_authentication: "Xác thực SMS OTP",
  otp_has_been_sent_to_your_phone_number: "Mã OTP đã được gửi đến số phone",
  please_enter_OTP_to_continue: "vui lòng nhập OTP để tiếp tục",
  the_system_has_recorded_your_transaction_and_the_transaction_will_be_processed_within_30_minutes_please_wait:
    "Hệ thống đã ghi nhận giao dịch của bạn và giao dịch sẽ được xử lý trong vòng 30 phút, vui lòng chờ!",
  circulating: "Đang lưu thông",
  this_feature_is_only_operated_on_the_computer:
    "Tính năng này chỉ được thao tác trên máy tính",
  comment_successfully: "Bình luận thành công",
  verify_withdrawal_order: "Xác thực lệnh rút",
  recharge_now: "Nạp tiền ngay",
  transaction_confirmation: "Xác nhận giao dịch",
  you_must_have_read_and_understood_about_this_product:
    "Bạn chắc chắn đã đọc và hiểu về sản phẩm này",
  you_agree_and_undertake_to_comply_with_the_release_and_withdrawal_policies_listed_in_the_Legal_tab:
    "Bạn đồng ý và cam kết tuân thủ với chính sách phát hành và chính sách thu hồi được liệt kê trong tab Pháp lý",
  you_are_solely_responsible_for_this_decision:
    "Bạn chịu hoàn toàn trách nhiệm về quyết định này",
  don_t_ask_again: "Không hỏi lại nữa",
  disagree: "Không đồng ý",
  agree: "Đồng ý",
  please_enter_the_OTP_sent_to_your_phone_number:
    "Vui lòng nhập OTP đã được gửi về số điện thoại",
  wrong_wallet_address: "Sai địa chỉ ví",
  correct_wallet_address: "Địa chỉ ví đúng",
  wallet_connection_is_not_completed: "Kết nối ví chưa hoàn tất",
  confirmed_transfer: "Xác nhận đã chuyển khoản",
  transaction_successful: "Giao dịch thành công",
  transaction_failed: "Giao dịch thất bại",
  check_your_metamask_network: "Kiểm tra mạng metamask của bạn",
  we_currently_do_not_support_this_network:
    "Hiện tại chúng tôi chưa hỗ trợ mạng này",
  please_select_your_network_to_continue:
    "Vui lòng chuyển mạng của bạn để tiếp tục",
  network_switch_in_wallet: "Chuyển đổi mạng trong ví",
  developing: "Đang phát triển",
  not_connected_to_the_network: "Chưa kết nối mạng",
  about_paragraph_1:
    "là nền tảng (platform) công nghệ đầu tiên tại Việt Nam áp dụng mô hình mua chung trong lĩnh vực đầu tư bất động sản.",
  about_paragraph_2:
    "RETX ứng dụng công nghệ Blockchain để số hoá Bất động sản (BĐS) thành tài sản số trên nền tảng Blockchain. Mỗi BĐS sẽ được phát hành riêng 1 loại Security Token gọi là Token chứng khoán. Mỗi token ứng với 1/1000 giá trị của BĐS. Cơ chế này giúp nhà đầu tư nhỏ lẻ trên thị trường cũng đủ năng lực “cùng mua” vào BĐS giá trị lớn.",
  about_paragraph_3:
    "Với giao thức chuyển đổi bất động sản thành tài sản số này, RETX mở ra cơ hội đầu tư vào thị trường bất động sản Việt Nam đầy tiềm năng chỉ bằng vài thao tác.",
  about_paragraph_4: "TẠI SAO LẠI CHỌN RETX?",
  about_paragraph_5:
    "Giúp người bán tiếp cận được hàng triệu nhà đầu tư cùng một lúc. Vì thế, bất động sản dễ dàng bán hơn và được bán với giá tốt hơn.",
  about_paragraph_6:
    "RETX góp phần làm nên thanh khoản của thị trường và giúp các nhà đầu tư mua – bán. Giao dịch dể dàng, minh bạch hơn.",
  about_paragraph_7:
    "RETX có thể truy xuất nguồn gốc giao dịch. Lịch sử giao dịch ứng với mỗi định danh được lưu trữ an toàn và dễ dàng kiểm tra nhanh chóng.",
  about_paragraph_8:
    "RETX – GIẢI PHÁP CHO THỊ TRƯỜNG BẤT ĐỘNG SẢN KHÔNG CÓ TRUNG GIAN",
  about_paragraph_9:
    "Các nhà môi giới, luật sư và ngân hàng từ lâu đã trở thành một phần của hệ sinh thái bất động sản. Tuy nhiên, giờ đây RETX có thể thay đổi vai trò đó trong các giao dịch bất động sản. Các chức năng của RETX có thể đảm nhận các chức năng như niêm yết, thanh toán và cung cấp tài liệu pháp lý.",
  about_paragraph_10:
    "Việc cắt bỏ bên trung gian sẽ giúp người mua và người bán tối uu hóa lợi nhuận hơn vì họ tiết kiệm được hoa hồng và phí dành cho các bên trung gian này. Điều này cũng làm cho quá trình giao dịch trở nên nhanh gọn hơn nhiều.",
  about_paragraph_11: "AN TOÀN VÀ BẢO MẬT",
  about_paragraph_12:
    "Giao dịch tại RETX chỉ thành công khi các định danh đã được xác minh và lịch sử giao dịch ứng với mỗi định danh sẽ được lưu trữ an toàn và dễ dàng kiểm tra nhanh chóng. Đồng thời, RETX chỉ mã hóa những bất động sản đảm bảo theo Pháp luật Việt Nam và đơn vị thẩm định. RETX cũng sẽ tự động tính thuế, phí trên mỗi giao dịch ứng với quy định hiện hành của khung thử nghiệm Sandbox.",
  about_paragraph_13: "CƠ HỘI CHO CÁC NHÀ ĐẦU TƯ NHỎ",
  about_paragraph_14:
    "Việc chia nhỏ giá trị bất động sản (Tokenization) sẽ tạo ra sân chơi cho mọi người, đặc biệt là các nhà đầu tư nhỏ lẻ. Thay vì phải có hàng trăm triệu hoặc hàng chục tỷ mới có thể sở hữu được bất động sản, nhưng với nền tảng RETX, các nhà đầu tư nhỏ với rất ít tiền cũng có thể đầu tư.",
  about_paragraph_15: "CÔNG CỤ HỖ TRỢ CHO CÁC CHỦ DỰ ÁN",
  about_paragraph_16:
    "Ngày nay, do tình hình dịch kéo dài khiến nhiều nhà đầu tư bất động sản gặp khó khăn khi bán BĐS hoặc dự án. Nắm bắt được nhu cầu đó, RETX ra đời không chỉ phục vụ cho người bán mà còn hỗ trợ các chủ dự án tiếp cận với cách thức huy động vốn mới, tháo gỡ những ách tắc trong quá trình thanh khoản của thị trường",
  about_paragraph_0: "GIỚI THIỆU VỀ RETX",
  project: "Dự án",
  price_not_updated_yet: "Chưa cập nhật giá",
  seller: "Bên bán",
  property_type: "Loại tài sản",
  direction: "Hướng",
  location: "Vị trí",
  area: "Diện tích",
  valuation: "Định giá",
  releasePolicy: "Chính sách phát hành",
  recoveryPolicy: "Chính sách thu hồi",
  legalOfProperty: "Pháp lý của tài sản",
  valuation_level: "Mức định giá",
  effect: "Ảnh hưởng",
  valuation_unit: "Đơn vị định giá",
  notarization_unit: "Đơn vị công chứng",
  notarization_date: "Ngày công chứng",
  parties_join_in_notarization: "Các bên tham gia công chứng",
  inspection_unit: "Đơn vị kiểm định",
  inspection_date: "Ngày kiểm định",
  main_content: "Nội dung chính",
  view_file_scan: "Xem bản scan",
  legal_documents_have_been_NFTized: "Hồ sơ pháp lý đã được NFT hoá",
  product_is_being_protected_by: "Tài sản đang được bảo về bởi",
  red_book: "Sổ đỏ",
  have_red_book: "Có sổ đỏ",
  have_not_red_book: "Không có sổ đỏ",
  dispute: "Tranh chấp",
  have_dispute: "Có tranh chấp",
  have_not_dispute: "Không có tranh chấp",
  stop_trading: "Tạm dừng giao dịch",
  view_public_records_at_IPFS: "Xem hồ sơ công khai tại IPFS",
  sorted_by: "Sắp xếp theo",
  creation_time: "Thời gian tạo",
  count_view: "Lượt xem",
  discussion: "Thảo luận",
  total_supply: "Tổng cung",
  oldest: "Cũ nhất",
  most: "Nhiều nhất",
  least: "Ít nhất",
  highest: "Cao nhất",
  lowest: "Thấp nhất",
  choose_a_seller: "Chọn người bán",
  choose_an_asset_type: "Chọn loại tài sản",
  choose_direction: "Chọn hướng",
  choose_city: "Chọn thành phố",
  choose_district: "Chọn quận/huyện",
  choose_ward: "Chọn phường/xã",
  unchecked: "Bỏ chọn",
  project_owner: "Chủ dự án",
  choose_a_project_owner: "Chọn chủ dự án",
  type_project: "Loại dự án",
  select_a_project_type: "Chọn loại dự án",
  issue: "Phát hành",
  purpose: "Mục đích",
  policy_and_legal_status_of_und_unit:
    "Chính sách và pháp lý của Chứng Chỉ Quỹ",
  information_and_legality_of_the_collateral:
    "Thông tin và pháp lý của Tài Sản đảm bảo",
  lock_content_1:
    "Bảo vệ và đảm bảo tài sản không được đổi chủ trong thời gian dự án đang đang hoạt động trên ứng dụng RETX",
  lock_content_2:
    "Giải phóng tài sản khi các điều khoản trong hồ sơ thu hồi được thõa mãn",
  lock_content_3:
    "Phối hợp xử lý tài sản trong trường hợp chủ dự án không tuân thủ hoặc mất khả năng thực hiện nghĩa vụ đã cam kết (để bồi thường quyền lợi cho nhà đầu tư)",
  is_responsible_for: "có trách nhiệm",
  lock: "Khoá",
  project_procedures: "Hồ sơ dự án",
  project_procedures_title_box:
    "Để đảm bảo tính toàn vẹn và minh bạch, hồ sơ dự án được NFT hóa tại địa chỉ",
  swap_note_1:
    "Vì RETX không nắm giữ tài sản của bạn, vậy nên RETX cần được ủy quyền để thực hiện giao dịch này",
  swap_note_2:
    "RETX đã được bạn ủy quyền để thực hiện giao dịch, bấm TIẾP THEO để giao dịch được thực thi",
  there_are_number_search_results_for_the_keyword:
    "Có :number kết quả tìm kiếm cho từ khóa",
  exact_search: "Tìm kiếm chính xác",
  retx_automatically_optimizes_the_buy_price_at_the_lowest_level:
    "RETX tự động tối ưu chi phí mua ở mức thấp nhất",
  over_pool_size: "Vượt pool size",
  product_suggested: "Sản phẩm gợi ý",
  term: "Điều khoản",
  you_need_to_connect_the_wallet: "Bạn cần kết nối ví Metamask",
  the_account_does_not_exist_in_the_system:
    "Tài khoản chưa tồn tại trong hệ thống",
  identity_verification_to_set_up: "Xác thực danh tính để thiết lập",
  awaiting_identity_verification: "Đang chờ xác thực danh tính",
  project_information: "Thông tin dự án",
  avatar: "Ảnh đại diện",
  basic_information: "Thông tin cơ bản",
  verify_now: "Xác thực ngay",
  view_results: "Xem kết quả",
  section_filter: "Bộ lọc",
  percentage: "Phần trăm",
  you_have_request_more_than_allowed: "Bạn đã yêu cầu vượt quá số lần cho phép",
  transfers: "Chuyển tiền",
  authorization_failed_please_try_again_later:
    "Uỷ quyền thất bại, vui lòng thử lại sau",
  web3_data_retrieval_failed: "Lấy dữ liệu web3 không thành công",
  not_open_for_sale_yet: "Chưa mở bán",
  register_success: "Đăng ký thành công",
  certificate_of_investment: "Chứng chỉ đầu tư",
  certificate_of_ownership: "Chứng chỉ sở hữu",
  price_fluctuations: "Biến động giá",
  certificate_type: "Loại chứng chỉ",
  product: "Sản phẩm",
  investment: "Đầu tư",
  own: "Sở hữu",
  "explore-section-paragraph-1":
    "Trở thành Nhà đầu tư Bất động sản ngay hôm nay",
  "explore-section-paragraph-2":
    "Khoản đầu tư được bảo đảm bằng bất động sản thực",
  explore_now: "Khám phá ngay",
  owner_information: "Thông tin chủ sở hữu",
  join_date: "Ngày tham gia",
  product_order_number: "Số thứ tự sản phẩm",
  numerical_order: "Số thứ tự",
  choose: "Chọn",
  product_name: "Tên sản phẩm",
  description: "Mô tả",
  do_you_own_this_product: "Bạn đang sở hữu sản phẩm này",
  you_have_not_posted_this_product_for_sale_yet:
    "Bạn chưa đăng bán sản phẩm này",
  sell_now: "Bán ngay",
  you_are_selling_this_product: "Bạn đang bán sản phẩm này",
  cancel_sale: "Huỷ bán",
  owner: "Chủ sở hữu",
  buy_now: "Mua ngay",
  you_have_made_an_offer_do_you_want_to_cancel_to_continue:"Bạn đã đưa ra đề nghị, bạn có muốn huỷ để tiếp tục",
  offer_to_negotiate:"Đưa ra đề nghị",
  your_balance_is_not_enough_do_you_want_to_top_up_to_continue: "Số dư của bạn không đủ, bạn có muốn nạp tiếp để tiếp tục",
  yes: "Có",
  no: "Không",
  the_product_is_not_for_sale: "Sản phẩm chưa được rao bán",
  the_owner_has_not_posted_this_product_for_sale: "Chủ sở hữu chưa đăng bán sản phẩm này",
  contact_the_owner: "Liên hệ chủ sở hữu",
  cancel: "Huỷ",
  negotiable_List: "Danh sách đề nghị",
  mine: "Của tôi",
  negotiating_party: "Bên trả giá",
  desired_price: "Giá mong muốn",
  action: "Hành động",
  agree_to_sell:"Đồng ý bán",
  suggested_purchase_price: "Giá mua đề xuất",
  transaction_fee: "Phí giao dịch",
  amount_earned: "Số tiền thu được",
  i_agree_to_and_abide_by_RETX_policy: "Tôi xác nhận đồng ý và tuân thủ :RETX_policy",
  RETX_policy: "chính sách của RETX",
  amount_you_have_to_pay: "Số tiền bạn phải thanh toán",
  amount_received_by_the_seller: "Số tiền bên bán nhận được",
  user_unregistered_address: "Địa chỉ chưa đăng ký người dùng",
  cancellation_of_negotiation: "Huỷ trả giá",
  desired_selling_price: "Giá bán mong muốn",
  desired_purchase_price: "Giá mua mong muốn",
  you_need_to_agree_to_the_terms: "Bạn cần đồng ý với điều khoản",
  minimum_price_is: "Giá tối thiểu là :amount",
  for_sale: "Rao bán",
  trading_results:"Kết quả giao dịch",
  trading_code: 'Mã giao dịch',
  close: 'Đóng',
  amount_of_assets: "Số lượng tài sản",
  owned_asset: "Tài sản đang sở hữu",
  asset_is_paying_price: "Tài sản đang trả giá",
  see_price_negotiable: 'Xem trả giá',
  circulate: "Lưu thông",
  trading: "Đang giao dịch",
  type: "Loại",
  resend_OTP_successfully: "Gửi lại mã OTP thành công",
  removed_from_cart_successfully: "Xóa khỏi giỏ hàng thành công",
  single_asset: "Tài sản Đầu tư",
  collection_asset: "Tài sản Sở hữu",
  pause_calling_for_capital: "Tạm dừng gọi vốn",
  pool_is_not_open_yet: "Chưa mở Pool",
  certificate: "Chứng chỉ",
  selling_price: "Giá rao bán",
  negotiate: "Trả giá"
};
